import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import '@radix-ui/themes/styles.css';
import './globals.css';
import NavBar from './NavBar';
import { Theme, ThemePanel } from '@radix-ui/themes';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Theme accentColor='blue'>
					<NavBar />
					<main className='p-5'>{children}</main>
					{/* <ThemePanel /> */}
				</Theme>
			</body>
		</html>
	);
}
